@tool
extends McpTestSuite

## The three placeholder icons the DayStickyNote template needs but that have
## no real art yet (Wirausaha / Istirahat / national holiday). Generated by
## Scripts/Design/GenerateStickyNoteIcons.gd (an EditorScript, File > Run).
## This suite is a plain asset-existence scan -- it instantiates nothing.

func suite_name() -> String:
	return "sticky_note_assets"

const _ICONS := [
	"res://Assets/Images/AturJadwal/icon_wirausaha_placeholder.png",
	"res://Assets/Images/AturJadwal/icon_istirahat_placeholder.png",
	"res://Assets/Images/AturJadwal/icon_libur_nasional_placeholder.png",
]

func test_placeholder_icons_exist_and_are_256_square() -> void:
	for path in _ICONS:
		assert_true(ResourceLoader.exists(path), "missing generated icon: " + path)
		var tex := load(path) as Texture2D
		assert_true(tex != null, path + " did not load as a Texture2D")
		if tex != null:
			assert_eq(tex.get_width(), 256, path + " must be 256 px wide")
			assert_eq(tex.get_height(), 256, path + " must be 256 px tall")

func test_generator_script_exists_and_is_documented() -> void:
	var p := "res://Scripts/Design/GenerateStickyNoteIcons.gd"
	assert_true(ResourceLoader.exists(p), "generator script is missing")
	var src := FileAccess.get_file_as_string(p)
	assert_true(src.begins_with("@tool"), "generator must be @tool")
	assert_true(src.contains("extends EditorScript"), "generator must extend EditorScript")
	assert_true(src.contains("## "), "generator needs a ## doc header")

func test_soft_shadow_shader_exists() -> void:
	var p := "res://Scripts/Shaders/soft_shadow.gdshader"
	assert_true(ResourceLoader.exists(p), "soft_shadow.gdshader is missing")
	var src := FileAccess.get_file_as_string(p)
	assert_true(src.contains("shader_type canvas_item"), "must be a canvas_item shader")
	assert_true(src.contains("uniform float blur"), "must expose a `blur` uniform")
	var sh := load(p) as Shader
	assert_true(sh != null, "did not load as a Shader resource")
