@tool
extends RefCounted

## GENERATED by ci/clean_code_dump.gd: the clean-code ratchet's baselines
## (docs/superpowers/design/clean-code.md). Every number here may only go
## DOWN. Never edit this file by hand, and never hand-merge a conflict in
## it: take one side whole, then run the dump. A growth is fixed in the
## code (reviewed exceptions: ci/clean_code_allowed.gd's four lists only).
## After an improvement, regenerate with the command below. If any entry
## would be added or raised, it writes nothing at all: it prints each one
## as a `RAISED (review):` line and exits 1.
##     <Godot console exe> --headless --path . --script res://ci/clean_code_dump.gd
## After a move, rename or split, re-key: it writes every entry and prints
## the RAISED lines as warnings -- the same numbers under new keys:
##     <Godot console exe> --headless --path . --script res://ci/clean_code_dump.gd -- --rekey

## Functions over 50 code lines: "path::function" -> code lines.
const LONG_FUNCTIONS: Dictionary = {
	"res://Scripts/AturJadwal/AturJadwal.gd::_build_tutorial_panel": 62,
	"res://Scripts/AturJadwal/AturJadwal.gd::_show_holiday_warning": 75,
	"res://Scripts/AturJadwal/AturJadwal.gd::_show_step": 59,
	"res://Scripts/AturJadwal/AturJadwal.gd::_update_student_display": 64,
	"res://Scripts/Debug/DebugManager.gd::_build_achievements_panel": 95,
	"res://Scripts/Debug/DebugManager.gd::_build_general_panel": 240,
	"res://Scripts/Debug/DebugManager.gd::_build_minigames_panel": 106,
	"res://Scripts/Debug/DebugManager.gd::_build_scenes_panel": 76,
	"res://Scripts/Debug/DebugManager.gd::_build_ui": 96,
	"res://Scripts/Debug/DebugManager.gd::_rebuild_student_stat_editor": 125,
	"res://Scripts/Lobby/Lobby.gd::_ready": 64,
	"res://Scripts/Lobby/Lobby.gd::_show_step": 56,
	"res://Scripts/Minigames/Akademis/Menjodohkan.gd::_instantiate_cards": 64,
	"res://Scripts/Minigames/Akademis/Menjodohkan.gd::reveal_answers": 60,
	"res://Scripts/Minigames/Akademis/Menjodohkan.gd::setup_game": 55,
	"res://Scripts/Minigames/Akademis/PilihanGanda.gd::_show_current_question": 70,
	"res://Scripts/Minigames/Akademis/Variabel.gd::_generate_question": 127,
	"res://Scripts/Minigames/Olahraga/Badminton.gd::_physics_process": 53,
	"res://Scripts/Minigames/Olahraga/Badminton.gd::_ready": 63,
	"res://Scripts/Minigames/Olahraga/MainBola.gd::_setup_layout": 95,
	"res://Scripts/Minigames/Olahraga/MainBola.gd::_shoot_ball": 57,
	"res://Scripts/Minigames/SeniBudaya/BuatBatik.gd::_apply_visual_exports": 53,
	"res://Scripts/Minigames/SeniBudaya/BuatBatik.gd::reveal_answers": 81,
	"res://Scripts/Minigames/UI/BaseMinigame.gd::_show_result_overlay": 56,
	"res://Scripts/Minigames/UI/MinigameResultPopup.gd::configure": 59,
	"res://Scripts/Minigames/UI/MinigameResultPopup.gd::play": 61,
	"res://Scripts/Pengaturan.gd::_ready": 73,
	"res://Scripts/SchoolSimulation/SchoolDay.gd::_play_minigame": 85,
	"res://Scripts/SchoolSimulation/SchoolDay.gd::_run_event": 72,
	"res://Scripts/SchoolSimulation/SchoolDay.gd::_run_single_day": 83,
	"res://Scripts/SchoolSimulation/SchoolDay.gd::skip_to_results": 54,
	"res://Scripts/SchoolSimulation/SimulationBackground.gd::_draw": 69,
	"res://Scripts/SchoolSimulation/StudentData.gd::apply_jadwal_activity": 60,
	"res://Scripts/SchoolSimulation/StudentData.gd::apply_minigame_result": 68,
	"res://Scripts/SchoolSimulation/StudentManager.gd::apply_daily_decay_all": 90,
	"res://Scripts/StudentCard/StudentCard.gd::_highlight_multiple": 54,
	"res://Scripts/StudentCard/StudentCard.gd::_populate_default_tutorial_steps": 52,
	"res://Scripts/StudentCard/StudentCard.gd::_ready": 74,
	"res://Scripts/StudentCard/StudentCard.gd::_show_step": 60,
	"res://Scripts/StudentCard/StudentCard.gd::_transition_page": 61,
	"res://Scripts/StudentList/StudentList.gd::_setup_students": 55,
	"res://Scripts/StudentList/StudentList.gd::_show_step": 53,
}

## Untyped vars, signatures without ->, untyped parameters, per script.
const UNTYPED: Dictionary = {
	"res://Scripts/AnimUtils.gd": 27,
	"res://Scripts/AturJadwal/AturJadwal.gd": 198,
	"res://Scripts/CutScene/CutScene.gd": 14,
	"res://Scripts/CutScene/HintLabel.gd": 3,
	"res://Scripts/Debug/DebugManager.gd": 169,
	"res://Scripts/Debug/EndGameRehearsal.gd": 2,
	"res://Scripts/GameSettings.gd": 2,
	"res://Scripts/GameState.gd": 9,
	"res://Scripts/Inventory/ApplyItemScreen.gd": 4,
	"res://Scripts/Inventory/ApplyStudentRow.gd": 3,
	"res://Scripts/Inventory/ItemDatabase.gd": 12,
	"res://Scripts/Koperasi/Koperasi.gd": 9,
	"res://Scripts/Koperasi/KoperasiStage.gd": 30,
	"res://Scripts/LevelSelect/AmplopCard.gd": 1,
	"res://Scripts/Lobby/Lobby.gd": 102,
	"res://Scripts/Lobby/StudentChatterPicker.gd": 2,
	"res://Scripts/Minigames/Akademis/Menjodohkan.gd": 70,
	"res://Scripts/Minigames/Akademis/Password.gd": 10,
	"res://Scripts/Minigames/Akademis/PilihanGanda.gd": 27,
	"res://Scripts/Minigames/Akademis/Variabel.gd": 66,
	"res://Scripts/Minigames/Olahraga/Badminton.gd": 52,
	"res://Scripts/Minigames/SeniBudaya/BuatBatik.gd": 46,
	"res://Scripts/Minigames/SeniBudaya/LombaMenari.gd": 40,
	"res://Scripts/Minigames/UI/BaseMinigame.gd": 30,
	"res://Scripts/Minigames/UI/MinigameMenu.gd": 7,
	"res://Scripts/Pengaturan.gd": 15,
	"res://Scripts/ReportCard/ReportCard.gd": 35,
	"res://Scripts/SchoolSimulation/DailyDecayOverview.gd": 26,
	"res://Scripts/SchoolSimulation/DaySummaryPopup.gd": 9,
	"res://Scripts/SchoolSimulation/EventStudentSelectDialog.gd": 2,
	"res://Scripts/SchoolSimulation/ResultCheckup.gd": 5,
	"res://Scripts/SchoolSimulation/SchoolDay.gd": 78,
	"res://Scripts/SchoolSimulation/SimulationBackground.gd": 36,
	"res://Scripts/SchoolSimulation/StudentData.gd": 8,
	"res://Scripts/SchoolSimulation/StudentManager.gd": 38,
	"res://Scripts/StudentCard/StudentCard.gd": 144,
	"res://Scripts/StudentCard/StudentCardView.gd": 13,
	"res://Scripts/StudentList/StudentList.gd": 92,
	"res://Scripts/TouchFeedback/TouchFeedbackEffect.gd": 17,
	"res://Scripts/TouchFeedback/TouchFeedbackManager.gd": 7,
	"res://Scripts/TutorialArrow.gd": 4,
}

## Bare numeric literals in function bodies, per script.
const BARE_NUMBERS: Dictionary = {
	"res://Scripts/Achievements/AchievementTile.gd": 1,
	"res://Scripts/Achievements/AchievementsScreen.gd": 1,
	"res://Scripts/AnimUtils.gd": 126,
	"res://Scripts/AturJadwal/ActivityPreview.gd": 6,
	"res://Scripts/AturJadwal/AturJadwal.gd": 90,
	"res://Scripts/AturJadwal/DayStickyNote.gd": 10,
	"res://Scripts/AturJadwal/ObjectiveHint.gd": 4,
	"res://Scripts/AturJadwal/SpecialtyMatchBurst.gd": 1,
	"res://Scripts/Audio/AudioDirector.gd": 10,
	"res://Scripts/CutScene/CutScene.gd": 7,
	"res://Scripts/CutScene/HintLabel.gd": 4,
	"res://Scripts/Debug/DebugLookPanel.gd": 19,
	"res://Scripts/Debug/DebugManager.gd": 309,
	"res://Scripts/Debug/EndGameRehearsal.gd": 3,
	"res://Scripts/Debug/WeekReportRehearsal.gd": 3,
	"res://Scripts/Design/GenerateParticleSprites.gd": 7,
	"res://Scripts/Design/GenerateStickyNoteIcons.gd": 25,
	"res://Scripts/Design/Juice.gd": 5,
	"res://Scripts/EndGame/EndCutscene.gd": 3,
	"res://Scripts/EndGame/ExamProgress.gd": 1,
	"res://Scripts/EndGame/RunGrade.gd": 1,
	"res://Scripts/EndGame/RunResult.gd": 4,
	"res://Scripts/EndGame/StarMeter.gd": 2,
	"res://Scripts/EndGame/StatCheck.gd": 1,
	"res://Scripts/EndGame/StatCheckRow.gd": 3,
	"res://Scripts/EndGame/WinStage.gd": 2,
	"res://Scripts/Feedback/HapticIndicator.gd": 2,
	"res://Scripts/Feedback/RewardFeedback.gd": 3,
	"res://Scripts/GameState.gd": 19,
	"res://Scripts/Inventory/ApplyItemScreen.gd": 24,
	"res://Scripts/Inventory/ApplyStudentRow.gd": 26,
	"res://Scripts/Inventory/Inventory.gd": 21,
	"res://Scripts/Inventory/InventorySlot.gd": 19,
	"res://Scripts/Inventory/ItemDetailSheet.gd": 41,
	"res://Scripts/Koperasi/BasketTray.gd": 7,
	"res://Scripts/Koperasi/ChatBubble.gd": 2,
	"res://Scripts/Koperasi/Koperasi.gd": 1,
	"res://Scripts/Koperasi/KoperasiStage.gd": 11,
	"res://Scripts/Koperasi/ShelfItem.gd": 5,
	"res://Scripts/Koperasi/TraySlot.gd": 2,
	"res://Scripts/LevelSelect/LevelSelect.gd": 2,
	"res://Scripts/Lobby/Lobby.gd": 43,
	"res://Scripts/Lobby/LobbyChatter.gd": 2,
	"res://Scripts/Lobby/StudentChatBubble.gd": 2,
	"res://Scripts/Lobby/StudentChatterCatalog.gd": 2,
	"res://Scripts/Lobby/StudentFace.gd": 3,
	"res://Scripts/Look/LookLayer.gd": 1,
	"res://Scripts/MainMenu/MainMenu.gd": 1,
	"res://Scripts/Minigames/Akademis/Menjodohkan.gd": 40,
	"res://Scripts/Minigames/Akademis/Password.gd": 4,
	"res://Scripts/Minigames/Akademis/PilihanGanda.gd": 5,
	"res://Scripts/Minigames/Akademis/Variabel.gd": 46,
	"res://Scripts/Minigames/Olahraga/Badminton.gd": 132,
	"res://Scripts/Minigames/Olahraga/MainBola.gd": 92,
	"res://Scripts/Minigames/Olahraga/ShuttlecockSprite.gd": 2,
	"res://Scripts/Minigames/SeniBudaya/BuatBatik.gd": 51,
	"res://Scripts/Minigames/SeniBudaya/LombaMenari.gd": 85,
	"res://Scripts/Minigames/UI/BaseMinigame.gd": 85,
	"res://Scripts/Minigames/UI/ConfettiFireworks.gd": 2,
	"res://Scripts/Minigames/UI/MinigameCountdown.gd": 4,
	"res://Scripts/Minigames/UI/MinigameMenu.gd": 10,
	"res://Scripts/Minigames/UI/MinigameResultPopup.gd": 31,
	"res://Scripts/Minigames/UI/MinigameWinScreen.gd": 6,
	"res://Scripts/Minigames/UI/ResultStar.gd": 7,
	"res://Scripts/Pengaturan.gd": 49,
	"res://Scripts/ReportCard/ReportCard.gd": 25,
	"res://Scripts/SchoolSimulation/DailyDecayOverview.gd": 12,
	"res://Scripts/SchoolSimulation/DaySummaryPopup.gd": 4,
	"res://Scripts/SchoolSimulation/DaySummaryStatRow.gd": 2,
	"res://Scripts/SchoolSimulation/DaySummaryStudentRow.gd": 6,
	"res://Scripts/SchoolSimulation/DayVerdict.gd": 2,
	"res://Scripts/SchoolSimulation/EventStudentSelectDialog.gd": 2,
	"res://Scripts/SchoolSimulation/EventWarning.gd": 3,
	"res://Scripts/SchoolSimulation/SchoolDay.gd": 54,
	"res://Scripts/SchoolSimulation/SimulationBackground.gd": 20,
	"res://Scripts/SchoolSimulation/StudentData.gd": 19,
	"res://Scripts/SchoolSimulation/StudentManager.gd": 31,
	"res://Scripts/SchoolSimulation/StudentSummaryCard.gd": 4,
	"res://Scripts/SchoolSimulation/WeekRecap.gd": 1,
	"res://Scripts/SchoolSimulation/WeekRecapBanner.gd": 4,
	"res://Scripts/Skins/BakeSkinPortraits.gd": 4,
	"res://Scripts/Skins/SkinCard.gd": 1,
	"res://Scripts/Skins/SkinSelect.gd": 1,
	"res://Scripts/Splashscreen/Splashscreen.gd": 1,
	"res://Scripts/StudentCard/StudentCard.gd": 140,
	"res://Scripts/StudentCard/StudentCardView.gd": 37,
	"res://Scripts/StudentList/StudentList.gd": 37,
	"res://Scripts/TouchFeedback/TouchFeedbackEffect.gd": 28,
	"res://Scripts/TouchFeedback/TouchFeedbackManager.gd": 2,
	"res://Scripts/Transition/Transition.gd": 7,
	"res://Scripts/TutorialArrow.gd": 7,
	"res://Scripts/UI/StatBar.gd": 1,
}

## Function bodies (5+ code lines) identical in two or more files.
const DUPLICATE_GROUPS: Array[String] = [
	"res://Scripts/AturJadwal/AturJadwal.gd::_clear_highlight | res://Scripts/Lobby/Lobby.gd::_clear_highlight | res://Scripts/StudentList/StudentList.gd::_clear_highlight",
	"res://Scripts/AturJadwal/AturJadwal.gd::_get_button_display_name | res://Scripts/Lobby/Lobby.gd::_get_button_display_name | res://Scripts/StudentCard/StudentCard.gd::_get_button_display_name",
	"res://Scripts/Lobby/Lobby.gd::_on_btn_mouse_entered | res://Scripts/StudentList/StudentList.gd::_on_btn_mouse_entered",
	"res://Scripts/Lobby/Lobby.gd::_setup_button_juice | res://Scripts/ReportCard/ReportCard.gd::_setup_button_juice | res://Scripts/StudentCard/StudentCard.gd::_setup_button_juice | res://Scripts/StudentList/StudentList.gd::_setup_button_juice",
	"res://Scripts/Lobby/Lobby.gd::_start_prompt_blink | res://Scripts/StudentList/StudentList.gd::_start_prompt_blink",
	"res://Scripts/Minigames/Akademis/Password.gd::_finish_quiz | res://Scripts/Minigames/Akademis/Variabel.gd::_finish_quiz",
	"res://Scripts/Minigames/Akademis/Password.gd::_on_clear_pressed | res://Scripts/Minigames/Akademis/Variabel.gd::_on_clear_pressed",
	"res://Scripts/Minigames/Akademis/Password.gd::_set_input_disabled | res://Scripts/Minigames/Akademis/Variabel.gd::_set_input_disabled",
	"res://Scripts/ReportCard/ReportCard.gd::_animate_button_click_bounce | res://Scripts/StudentCard/StudentCard.gd::_animate_button_click_bounce",
	"res://Scripts/ReportCard/ReportCard.gd::_evaluate_swipe | res://Scripts/StudentCard/StudentCard.gd::_evaluate_swipe",
	"res://Scripts/ReportCard/ReportCard.gd::_get_stat_icon | res://Scripts/StudentCard/StudentCard.gd::_get_stat_icon",
	"res://Scripts/ReportCard/ReportCard.gd::_hide_card_rows | res://Scripts/StudentCard/StudentCard.gd::_hide_card_rows",
	"res://Scripts/ReportCard/ReportCard.gd::_on_btn_mouse_entered | res://Scripts/StudentCard/StudentCard.gd::_on_btn_mouse_entered",
	"res://Scripts/ReportCard/ReportCard.gd::_on_btn_mouse_exited | res://Scripts/StudentCard/StudentCard.gd::_on_btn_mouse_exited",
	"res://Scripts/ReportCard/ReportCard.gd::_show_bar_popup | res://Scripts/StudentCard/StudentCard.gd::_show_bar_popup",
	"res://Scripts/ReportCard/ReportCard.gd::_stagger_in_card | res://Scripts/StudentCard/StudentCard.gd::_stagger_in_card",
	"res://Scripts/SchoolSimulation/DailyDecayOverview.gd::_on_scroll_gui_input | res://Scripts/SchoolSimulation/EventStudentSelectDialog.gd::_on_scroll_gui_input | res://Scripts/SchoolSimulation/ResultCheckup.gd::_on_scroll_gui_input",
	"res://Scripts/StudentCard/StudentCard.gd::_next_step | res://Scripts/StudentList/StudentList.gd::_next_step",
	"res://Scripts/UI/StatDetailPopup.gd::close | res://Scripts/UI/TraitDetailPopup.gd::close",
	"res://Scripts/UI/StatDetailPopup.gd::open | res://Scripts/UI/TraitDetailPopup.gd::open",
]

## Scripts over 1,000 lines -> their line count.
const LARGE_SCRIPTS: Dictionary = {
	"res://Scripts/AturJadwal/AturJadwal.gd": 1578,
	"res://Scripts/Debug/DebugManager.gd": 1747,
	"res://Scripts/SchoolSimulation/SchoolDay.gd": 1637,
	"res://Scripts/StudentCard/StudentCard.gd": 1451,
}

## Must reach zero: .gd/.tscn names that are not PascalCase.
const BAD_SCRIPT_NAMES: Array[String] = [
]

## Must reach zero: scripts not named after their class_name.
const CLASS_NAME_MISMATCHES: Array[String] = [
]

## Must reach zero: asset names with characters outside A-Z a-z 0-9 _ - .
const BAD_ASSET_NAMES: Array[String] = [
]

## Must reach zero: file and folder names with a misspelled stem.
const MISSPELLED_NAMES: Array[String] = [
]

## Must stay zero: res:// literals naming nothing with that exact case.
const UNRESOLVED_PATHS: Array[String] = [
]

## Must reach zero: legacy stat keys per file.
const LEGACY_STAT_KEYS: Dictionary = {
}
